periodics:
- interval: 10m
  name: echo-test
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
presubmits:
  vitt-bagal/prow-test:
  - name: test-presubmit
    always_run: true
    skip_report: true
    context: test-presubmit
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
    trigger: "(?m)^/test this"
    rerun_command: "/test this"
